[tool.black]
line-length = 120
extend-exclude = ".*/conda_env/"

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["akdof_shared"]
known_local_folder = ["config", "core"]
extend_skip_glob = ["**/conda_env/*"]
ensure_newline_before_comments = true
force_sort_within_sections = true
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3

[tool.pytest.ini_options]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--tb=short",
]
markers = [
    "e2e: marks tests as end-to-end tests",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]
norecursedirs = [
    "config",
    "core",
    "data",
    "*.egg-info",
    "env",
    ".git",
    "__pycache__",
]
python_classes = "Test*"
python_files = "test_*.py"
python_functions = "test_*"
verbosity_assertions = 1
verbosity_test_cases = 1